version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo-test
    environment:
      MONGO_INITDB_DATABASE: electronix-db
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"
